# syntax=docker/dockerfile:1.6

FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY . .

ENV NODE_ENV=production
ENV PORT=3331
EXPOSE 3331

CMD ["node", "index.js"]
